apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edu16-prd

resources:
- ../../base

patches:
- path: ./deployment-patch.yaml
  target:
    kind: Deployment
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: ktdseduacr.azurecr.io/edu16/samplejava
  newName: ktdseduacr.azurecr.io/edu16/samplejava
  newTag: v1.0.2
